# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: MIT License

model:
  class_path: "IS2RELitModule"
  init_args:
    gnn:
      class_path: ocpmodels.models.PLEGNNBackbone
      init_args:
        # embed_in_dim: 1                          
        # embed_hidden_dim: 32                     
        # embed_out_dim: 128                        
        # embed_depth: 5                           
        # embed_feat_dims: [128,128,128]        
        # embed_message_dims: [128,128,128]        
        # embed_position_dims: [64, 64]            
        # embed_edge_attributes_dim: 0             
        # embed_activation: relu                   
        # embed_residual: True                     
        # embed_normalize: True                    
        # embed_tanh: True                         
        # embed_activate_last: False               
        # embed_k_linears: 1                       
        # embed_use_attention: False               
        # embed_attention_norm: sigmoid            
        # readout: sum                             
        # node_projection_depth: 3                 
        # node_projection_hidden_dim: 128          
        # node_projection_activation: relu         
        # prediction_out_dim: 1                    
        # prediction_depth: 3                      
        # prediction_hidden_dim: 128             
        # prediction_activation: relu    
        # num_vectors: 1   
        embed_in_dim: 1                          
        embed_hidden_dim: 32                     
        embed_out_dim: 32                   
        embed_depth: 3                        
        embed_feat_dims: [48, 48]
        embed_message_dims: [16, 16]        
        embed_position_dims: [64, 64]            
        embed_edge_attributes_dim: 0
        embed_activation: relu                   
        embed_residual: False
        embed_normalize: False
        embed_tanh: False
        embed_activate_last: False
        embed_k_linears: 1
        embed_use_attention: False
        embed_attention_norm: sigmoid
        readout: sum
        node_projection_depth: 3
        node_projection_hidden_dim: 128
        node_projection_activation: relu
        prediction_out_dim: 1
        prediction_depth: 3
        prediction_hidden_dim: 64
        prediction_activation: relu
        num_vectors: 10
    #regress_forces: True                       
    normalize_kwargs:                            
      target_mean: -0.7554450631141663            
      target_std: 2.887317180633545              
      grad_target_mean: 0.0                     
      grad_target_std: 2.887317180633545          
    lr: 0.003626         
    gamma: 0.6878