# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: MIT License

model:
  class_path: ocpmodels.models.IS2RELitModule
  init_args:
    gnn:
      class_path: ocpmodels.models.egnn.PLEGNNBackbone
      init_args:
        embed_in_dim: 1
        embed_hidden_dim: 32
        embed_out_dim: 32
        embed_depth: 3
        embed_feat_dims:
        - 48
        - 48
        embed_message_dims:
        - 16
        - 16
        embed_position_dims:
        - 64
        - 64
        embed_edge_attributes_dim: 0
        embed_activation: relu
        embed_residual: true
        embed_normalize: false
        embed_tanh: false
        embed_activate_last: true
        embed_k_linears: 1
        embed_use_attention: false
        embed_attention_norm: sigmoid
        readout: sum
        node_projection_depth: 2
        node_projection_hidden_dim: 128
        node_projection_activation: relu
        prediction_out_dim: 1
        prediction_depth: 3
        prediction_hidden_dim: 64
        prediction_activation: relu
        num_vectors: 1

    # regress_forces: true
    # gradient_clip_val: 0.2
    normalize_kwargs:
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    lr: 0.0001
    gamma: 0.5
    nan_check: false